### ISSUE TITLE
Problems with multisend tool

### ISSUE THREAD

**Issue by skr4th** [Jpja/CounterTools#17]
The Bitpay API has stopped working for me, and the blockchain.info API only sends the first transaction of the transactions plan. The second transactions with blockchain.info fails : "Please wait for previous transaction to confirm. It usually takes between 5 and 15 minutes." With Bitpay all the transactions worked well.

I've made many transactions from one single address, and after trying to send from a different address, the BitPay API started to work again, for a short period of time. Maybe they are blocking my sends. Would be nice to have more APIs for increased reliability.

**Comment by Jpja** [comment]
Indeed. More APIs will increase reliability.

**Comment by skr4th** [comment]
I'm closing this issue because the tool is working fine for me again: I noticed you can increase the 
API_TIMEOUT_MS in the settings/general.txt file. I doubled the value and it seems to do the trick!
